[colors.primary]
foreground = "#c6c6c6"
background = "#000000"

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "SF Mono", style = "Bold" }
size = 8.25

[mouse]
hide_when_typing = true

[terminal]
shell = "/opt/homebrew/bin/fish"
