[general]
import = [
	"colorscheme.toml"
]	

[window]
startup_mode = "Fullscreen"

[mouse]
hide_when_typing = true

[font]
normal = { family = "FiraCode", style = "Bold" }
size = 7

[terminal]
shell = { program = "fish" }
