" Global Settings:{{{

" Disable vi compatibility.
set nocompatible
" Enable support for 24-bit colors.
set termguicolors
" Print the line number in front of each line.
set number
" Do not use swapfiles.
set noswapfile
" Remove the '~' characters in the empty lines below the end of the buffer.
set fillchars=eob:\ 
" Always show a status line.
set laststatus=2
" Use markers to indicate folds.
set foldmethod=marker
" Highlight the line number of the cursor.
set cursorlineopt=number
" Always display the tab line.
set showtabline=2
" Set the content of the tab line.
set tabline=%!GenerateTabLine()
" Enable filetype based syntax highlighting.
syntax on
" Set the default colorscheme to 'moorabbit'.
colorscheme moorabbit

" }}}

" Global Variables:{{{

" Set the value of <Leader>.
let mapleader = "\\"
" Set the value of <LocalLeader>.
let maplocalleader = ","
" Generates the tab line content.
function GenerateTabLine()
	let s = ""

	for i in range(tabpagenr("$"))
		" Build the tab name from the tab local variable t:name.
		let tabname = i .. ":" .. gettabvar(i + 1, "name", "vim")

		" Highlight the tab labels.
		if i + 1 == tabpagenr()
			let s ..= "%#TabLineSel#"
		else
			let s ..= "%#TabLine#"
		endif

		let s ..= "%" .. (i + 1) .. "T" .. tabname

		" Add a marker for the active/inactive tabs.
		if i + 1 == tabpagenr()
			let s ..= "*"
		else
			let s ..= "-"
		endif

		" Add a small margin to the right of each tab label.
		let s ..= " "
	endfor

	" Highlight the rest of the tab line and reset the tab page number.
	" (see :help setting-tabline)
	let s ..= "%#TabLineFill#%T"

	return s
endfunction

" }}}

" Key Bindings:{{{

" Open $MYVIMRC in a new tab split.
nnoremap <Leader>ev :tab split $MYVIMRC<cr>
" Source $MYVIMRC.
nnoremap <Leader>sv :source $MYVIMRC<cr>

" Turn off the highlighted matches after a search.
nnoremap <silent> <c-l> :nohlsearch<cr><c-l>

" Line movement key bindings.
inoremap <c-r> <c-o>$
inoremap <c-q> <c-o>^
inoremap <c-j> <c-o>j
inoremap <c-k> <c-o>k
inoremap <c-l> <c-o>l
inoremap <c-h> <c-o>h
nnoremap <c-r> $
nnoremap <c-q> ^
vnoremap <c-r> $
vnoremap <c-q> ^

" Tab movement key bindings.
nnoremap <Leader>] :tabnext<cr>
nnoremap <Leader>[ :tabprevious<cr>

" }}}

" Commands:{{{

" Rename the current tab.
command! -nargs=1 TabRename let t:name = <q-args> | redrawtabline

" }}}
