# Options{{{

# Set the default terminal for new windows created in this session.
set-option -g default-terminal "alacritty"
# Specify the default shell. Must be the full path of the executable.
set-option -g default-shell "/usr/bin/fish"
# Tc Indicate that the terminal supports the ‘direct colour’
#    RGB escape sequence (for example, \e[38;2;255;255;255m).
set-option -sa terminal-overrides ",alacritty*:Tc"
# Automatically renumber the other windows in numerical order when a window is closed in a session.
set-option -g renumber-windows on
# Do not allow programs in the pane to change the window name.
set-option -g allow-rename off
# Switch to the prefix key table using C-s.
set-option -g prefix C-s
# Show the status line.
set-option -g status on

# }}}

# Style{{{

set-option -g status-style none

set-option -g status-justify centre

set-option -g status-left ""

set-option -g status-right ""

set-option -g window-status-current-style "fg=#ff7733"

# }}}

# Key bindings{{{

unbind-key C-b

unbind-key -T prefix c
bind-key   -T prefix n new-window

unbind-key -T prefix ]
bind-key   -T prefix ] next-window

unbind-key -T prefix [
bind-key   -T prefix [ previous-window

unbind-key -T prefix r
bind-key   -T prefix r source-file ~/.tmux.conf

unbind-key -T prefix %
bind-key   -T prefix | split-window -h

# }}}
